## Assignment 1: Bayesian Decision Theory and Parametric Estimation

- [ ] I. Loading the data and building a Gaussian Classifier
  - [x] a) Loading the Abalon Dataset. Ignoring the sex label and compute `rings_hat` which is the average value of rings of the whole data set
  - [x] b) Load the data as two numpy arrays `X` attributes and `y` labels
  - [x] c) Split the data set in training and validation
  - [ ] d) Build a Gaussian Classifier for each attribute.
    - [ ] Record parameters (I think those are mean and variance)
    - [ ] Accuracy, Precision & Recall
    - [ ] Which classifier is best
    - [ ] Draw curves for posterior distribution. Show decision boundary
- [ ] II. Bivariate models and ROC 
  - [ ] For each pair of features, create a bivariate Gaussian Classifier. The parameter of each of these models will be, the mean of the features BUT the covariance matrix will be of all of the classes.
  - [ ] For each combination, estimate the parameters to make predictions. Report results
  - [ ] Draw ROC curves for model of Q1 and these Q2 models
- [ ] III. Discriminant Functions & Regions
  - [ ] For the best model in Q2 draw regions
  - [ ] Calculate the decision boundary of the regions: Equation!
- [ ] IV. Regions for the best
  - [ ] For the best bivariate model in Q2 change the covariance matrix by a random one (could be different for each class *i dont quite understand this part*)
  - [ ] Draw regions
  - [ ] Add a rejection region 



## Como trabajar
Total: 28 modelos. 7 univariados y 21 bivariados.
14 modelos por grupo
### Univariados
- Length 
- Diameter
- Height
- Whole weight
- Shucked weight
- Viscera weight
- Shell weight


In [ ]:
import pandas as pd
import numpy as np
from math import floor
from sklearn import model_selection
from sklearn.naive_bayes import GaussianNB

In [ ]:
df_features = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data", 
                 names=["Sex","Length","Diameter","Height","Whole weight","Shucked weight","Viscera weight","Shell weight","Rings"])


In [ ]:
df_features.drop(columns=["Sex"], inplace=True)
df_features.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [ ]:
rings_hat= floor(df_features["Rings"].mean())
rings_hat

9

In [ ]:
df_features["Rings"] = np.where(df_features["Rings"] >= rings_hat, 1, 0)

In [ ]:
X = df_features.drop(columns=["Rings"]).to_numpy().astype('float')
X

array([[0.455 , 0.365 , 0.095 , ..., 0.2245, 0.101 , 0.15  ],
       [0.35  , 0.265 , 0.09  , ..., 0.0995, 0.0485, 0.07  ],
       [0.53  , 0.42  , 0.135 , ..., 0.2565, 0.1415, 0.21  ],
       ...,
       [0.6   , 0.475 , 0.205 , ..., 0.5255, 0.2875, 0.308 ],
       [0.625 , 0.485 , 0.15  , ..., 0.531 , 0.261 , 0.296 ],
       [0.71  , 0.555 , 0.195 , ..., 0.9455, 0.3765, 0.495 ]])

In [ ]:
y = df_features["Rings"].to_numpy().astype('float')
y

array([1., 0., 1., ..., 1., 1., 1.])

In [ ]:
train_features, train_labels, test_features, test_labels = model_selection.train_test_split(X, y, test_size=0.33, random_state=42)
train_features

array([[0.525 , 0.38  , 0.135 , ..., 0.261 , 0.159 , 0.175 ],
       [0.465 , 0.36  , 0.105 , ..., 0.172 , 0.107 , 0.175 ],
       [0.52  , 0.425 , 0.155 , ..., 0.297 , 0.123 , 0.255 ],
       ...,
       [0.51  , 0.395 , 0.125 , ..., 0.244 , 0.1335, 0.188 ],
       [0.575 , 0.465 , 0.12  , ..., 0.516 , 0.2185, 0.235 ],
       [0.595 , 0.475 , 0.16  , ..., 0.547 , 0.231 , 0.271 ]])

### d) Univariate Gaussian Classifier for each attribute
**Atributtes:**
- Length
- Diameter 
- Height 
- Whole weight
- Shucked weight
- Viscera weight
- Shell weight


#### Length

In [ ]:
X_length = X[:,0].astype('float')
X_length

array([0.455, 0.35 , 0.53 , ..., 0.6  , 0.625, 0.71 ])

In [ ]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X_length, y, test_size=0.33, random_state=42)


In [ ]:
model = GaussianNB()

In [ ]:
# Train the classifier on the training data
model.fit(X_train.reshape(-1, 1), y_train)


GaussianNB()

In [ ]:
predictions = model.predict(X_test.reshape(-1, 1))

In [ ]:
accuracy = model.score(X_test.reshape(-1, 1), y_test)
accuracy

0.7897026831036983